# Generated by Django 5.2.1 on 2025-05-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Fichier uploadé"),
                            ("github", "Dépôt GitHub"),
                        ],
                        max_length=10,
                    ),
                ),
                ("source_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("maintainability_index", models.FloatField(blank=True, null=True)),
                ("bugs_probability", models.FloatField(blank=True, null=True)),
                ("halstead_volume", models.FloatField(blank=True, null=True)),
                ("lcom4", models.FloatField(blank=True, null=True)),
                ("complexity", models.FloatField(blank=True, null=True)),
                ("source_metrics", models.TextField(blank=True, null=True)),
                ("pylint_score", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
